### ISSUE TITLE
error at start version 2.1

### ISSUE THREAD

**Issue by freakexeuLow** [maxijabase/calladmin-block#1]
I'm using the plugin via MySQL, it shows this error when starting from the server
```
L 10/03/2020 - 16:54:07: SourceMod error session started
L 10/03/2020 - 16:54:07: Info (map "bhop_darkling_v2_csgo") (file "/home/user2-2/server/csgo/csgo/addons/sourcemod/logs/errors_20201003.log")
L 10/03/2020 - 16:54:07: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 10/03/2020 - 16:54:07: [SM] Blaming: calladmin_block_sql.smx
L 10/03/2020 - 16:54:07: [SM] Call stack trace:
L 10/03/2020 - 16:54:07: [SM]   [0] Database.Query
L 10/03/2020 - 16:54:07: [SM]   [1] Line 120, C:\Users\Usuario\Documents\Github\calladmin-block\scripting\calladmin_block_sql.sp::OnClientPostAdminCheck
```

**Comment by maxijabase** [comment]
Just checked the plugin working perfectly in TF2. This is most likely caused by the database handle being invalid since the connection to the database never occured. When you reload the plugin or you start/restart the server, along everything the console spits, you should be able to identify if CallAdmin Block is throwing a database connection error.

**Comment by freakexeuLow** [comment]
> 
> 
> Just checked the plugin working perfectly in TF2. This is most likely caused by the database handle being invalid since the connection to the database never occured. When you reload the plugin or you start/restart the server, along everything the console spits, you should be able to identify if CallAdmin Block is throwing a database connection error.

I use it in CSGO....i have several other servers running with different gamemodes. I know what I am doing and I do not see the error on me. I'm going to ask one of my friends what the error is. As I said, I set everything correctly and got the same error on 2 servers.

Edit: Both servers were of course restarted

**Comment by maxijabase** [comment]
Welp nice opportunity to start testing plugins in CSGO as well, will open up a small dedicated and let you know if I manage to get a grasp about what the issue might be

**Comment by maxijabase** [comment]
I just used the plugin as I would normally do in a CS:GO server and works perfectly fine. Can you give out more details regarding the issue?

**Comment by freakexeuLow** [comment]
> 
> 
> I just used the plugin as I would normally do in a CS:GO server and works perfectly fine. Can you give out more details regarding the issue?

i tried to install the system on 4 servers, all should use the same database.... but i couldn't test much because of this error and i disabled the plugin now^^

**Comment by maxijabase** [comment]
Those are not the issue details I asked for, though.

**Comment by freakexeuLow** [comment]
> 
> 
> Those are not the issue details I asked for, though.

What exactly do you need? I have written it almost everything. My plugins are on the latest version, as well Sourcemod Version and Metamod Version. 

3 x Retake Server + 3 x Surf Server (Timer) that run with the system "Calladmin" only your system causes me problems, all other plugins I have run otherwise work without problems ^^

**Comment by maxijabase** [comment]
Do you have other plugins connected to this database and working? 
Can you properly access this DB from a client such as Navicat without problems?
I made an update some days ago that makes the plugin fail completely if it doesn't succeed in connecting to the database, and I just uploaded the compiled version of it. Furthermore, since the issue is happening when a client connects and plugin attempts to query him, I switched to the more reliable forward OnClientAuthorized. Make sure to test that to see if there's a problem in that side. Check the latest repo files.

**Comment by freakexeuLow** [comment]
> 
> 
> Do you have other plugins connected to this database and working?
> Can you properly access this DB from a client such as Navicat without problems?
> I made an update some days ago that makes the plugin fail completely if it doesn't succeed in connecting to the database, and I just uploaded the compiled version of it. Furthermore, since the issue is happening when a client connects and plugin attempts to query him, I switched to the more reliable forward OnClientAuthorized. Make sure to test that to see if there's a problem in that side. Check the latest repo files.

a list of my plugins that are linked to the database and work wonderfully: 2x BhopTimer, Chat Relay System, Stats System (FPS), gloves, kz (Climb), Level Ranks System, Store (Kxnrl) on 2 servers, Stickers, SurfTimer 3x, VPN and !ws Plugin....Do I have to use the Github version or the version (2.1) on Allied? Theoretically you can put everything in one plugin, it looks better^^

**Comment by maxijabase** [comment]
I uploaded the newest version I told you to download here, on GitHub. Let me know what happens.

**Comment by freakexeuLow** [comment]
sorry for the VERY late answer, but i tried the plugin again via mysql, when i try to ban people, there are these error logs

`L 02/24/2022 - 16:40:28: SourceMod error session started
L 02/24/2022 - 16:40:28: Info (map "de_mirage") (file "/home/user2-4/server/csgo/csgo/addons/sourcemod/logs/errors_20220224.log")
L 02/24/2022 - 16:40:28: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 02/24/2022 - 16:40:28: [SM] Blaming: calladmin_block_sql.smx
L 02/24/2022 - 16:40:28: [SM] Call stack trace:
L 02/24/2022 - 16:40:28: [SM]   [0] Database.Query
L 02/24/2022 - 16:40:28: [SM]   [1] Line 120, C:\Users\Usuario\Documents\Github\calladmin-block\scripting\calladmin_block_sql.sp::OnClientPostAdminCheck
L 02/24/2022 - 16:41:54: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 02/24/2022 - 16:41:54: [SM] Blaming: calladmin_block_sql.smx
L 02/24/2022 - 16:41:54: [SM] Call stack trace:
L 02/24/2022 - 16:41:54: [SM]   [0] Database.Query
L 02/24/2022 - 16:41:54: [SM]   [1] Line 283, C:\Users\Usuario\Documents\Github\calladmin-block\scripting\calladmin_block_sql.sp::CMD_Add
L 02/24/2022 - 16:42:19: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 02/24/2022 - 16:42:19: [SM] Blaming: calladmin_block_sql.smx
L 02/24/2022 - 16:42:19: [SM] Call stack trace:
L 02/24/2022 - 16:42:19: [SM]   [0] Database.Escape
L 02/24/2022 - 16:42:19: [SM]   [1] Line 254, C:\Users\Usuario\Documents\Github\calladmin-block\scripting\calladmin_block_sql.sp::CMD_Add`

when you restart the server, you got this issue: [https://github.com/maxijabase/calladmin-block/issues/2](https://github.com/maxijabase/calladmin-block/issues/2)

**Comment by maxijabase** [comment]
can you please download the latest version and try again?

**Comment by freakexeuLow** [comment]
> can you please download the latest version and try again?

Hey and the plugin works now, have no more errors and I am also entered in the db as it should be
