### ISSUE TITLE
Error upon starting up - Invalid Database Handle

### ISSUE THREAD

**Issue by MaranRoseGIT** [maxijabase/calladmin-block#2]
There should be a check if the database connection was established, but I think it's missing client validation, about something with "SQL_OnClientConnectedCacheCallback"? (this is what someone told me atleast) This error has only started happening recently, don't exactly know what to do about it. (Image is below, rather new to Git, sorry!)

**Comment by MaranRoseGIT** [comment]
![image](https://user-images.githubusercontent.com/80443691/116969915-1487bd00-ac85-11eb-8e93-7ee50b19f718.png)

**Comment by maxijabase** [comment]
fixed in latest release
